---
## tasks file for install_cephadm
- name: Download cephadm
  get_url:
    url: https://github.com/ceph/ceph/raw/pacific/src/cephadm/cephadm
    dest: /root/cephadm
    mode: '0755'

- name: Add repo cephadm
  shell: "/root/cephadm add-repo --release pacific"
  args:
    executable: /bin/bash

- name: Install cephadm
  shell: "/root/cephadm install"
  args:
    executable: /bin/bash

- name: Add repo with cephadm
  shell: "cephadm add-repo --release pacific"

- name: Install ceph-common
  shell: "cephadm install ceph-common"
