---
## tasks file for install_cephadm
- name: install package
  package:
    name: epel-release
    state: present
  register: result
  until: result is succeeded

- name: remove remaining local services ceph packages
  dnf:
    name: "{{ packages_to_uninstall }}"
    state: absent
    autoremove: false

- name: install ceph-common on rhel
  package:
    name: ceph-common
    state: "{{ (upgrade_ceph_packages | bool) | ternary('latest', 'present') }}"
  register: result
  until: result is succeeded

- name: install prerequisites packages on servers
  package:
    name: "{{ ceph_pkgs + infra_pkgs }}"
    state: "{{ (upgrade_ceph_packages | bool) | ternary('latest', 'present') }}"
  register: result
  until: result is succeeded
  when: group_names != [client_group]

- name: install prerequisites packages on clients
  package:
    name: "{{ ceph_client_pkgs }}"
    state: "{{ (upgrade_ceph_packages | bool) | ternary('latest', 'present') }}"
  register: result
  until: result is succeeded
  when: group_names == [client_group]


- name: ensure chronyd is running
  service:
    name: chronyd
    state: started
    enabled: true
