---
# defaults file for install_cephadm
upgrade_ceph_packages: false
ceph_pkgs:
  - cephadm
  - ceph-common
ceph_client_pkgs:
  - chrony
  - ceph-common
infra_pkgs:
  - chrony
  - podman
client_group: clients
packages_to_uninstall:
  - ceph-mds
  - ceph-mgr
  - ceph-mon
  - ceph-osd
  - ceph-radosgw
  - rbd-mirror
