# Install Cephadm
- name: Install Cephadm
  gather_facts: false
  become: true
  hosts: all
  roles:
    - { role: install_cephadm,
        tags: install_cephadm }

## Install Cephadm
#- name: Cephadm Bootstrap
#  gather_facts: false
#  become: true
#  hosts: "{{ groups['admin'][0] }}"
#  roles:
#    - { role: cephadm_bootstrap,
#        tags: cephadm_bootstrap }
