meta:  
  host: ceph03-quincy
  ip: 192.168.70.63
  labels:
  - osd
  blockdb:
  - /dev/vdb
  ssd:
  - /dev/vdc
  - /dev/vdd
  - /dev/vde

# osd_objectstore: Chon bluestore hoac filestore
osd_objectstore: bluestore
crush_device_class: hdd
