meta:  
  host: cephbk02
  ip: 192.168.70.65
  labels:
  - osd
  hdd:
  - /dev/vdb
  - /dev/vdc

# osd_objectstore: Chon bluestore hoac filestore
osd_objectstore: bluestore
crush_device_class: backup
